---- Base app schema

-- User
CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  username varchar(128) NOT NULL UNIQUE,

  -- Auth
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid()
);

--Feelings
CREATE TABLE feeling (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  f_name varchar(256) NOT NULL
);

insert into feeling(id, f_name) values (1, 'flying');
insert into feeling(id, f_name) values (2, 'swollen fingers');



CREATE TABLE user_has_feeling (
  u_id BIGINT,
  f_id BIGINT,
  f_value BIGINT,
  insert_time timestamp 
);

insert into user_has_feeling(u_id, f_id,f_value,insert_time) values (1,1,3, '2023-9-17 11:30:30');
insert into user_has_feeling(u_id, f_id,f_value,insert_time) values (1,1,2, '2023-9-18 11:30:30');
insert into user_has_feeling(u_id, f_id,f_value,insert_time) values (1,1,5, '2023-9-19 11:30:30');

insert into user_has_feeling(u_id, f_id,f_value,insert_time) values (1,2,3, '2023-9-17 11:30:30');
insert into user_has_feeling(u_id, f_id,f_value,insert_time) values (1,2,2, '2023-9-18 11:30:30');
insert into user_has_feeling(u_id, f_id,f_value,insert_time) values (1,2,5, '2023-9-19 11:30:30');

CREATE TABLE user_2_feeling (
  u_id BIGINT,
  id BIGINT
);

insert into user_2_feeling(u_id, id) values (1,1);
insert into user_2_feeling(u_id, id) values (1,2);
--Ingredients
CREATE TABLE ingredient (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name varchar(256) NOT NULL,
  allergy_information varchar(256)
);

CREATE TABLE user_has_ingredient (
  u_id BIGINT,
  i_id BIGINT,
  gram BIGINT,
  insert_time timestamp 
);

CREATE TABLE user_2_ingredient (
  u_id BIGINT,
  id BIGINT
);

CREATE TABLE meal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  name varchar(256) NOT NULL
);

CREATE TABLE meal_2_ingredients (
  m_id BIGINT,
  i_id BIGINT
);

CREATE TABLE user_2_meal (
  u_id BIGINT,
  id BIGINT
);




